version: "3.8"

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native TCP interface
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: mysecret
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./default-user-password.xml:/etc/clickhouse-server/users.d/default-user-password.xml:ro

volumes:
  clickhouse_data:
  clickhouse_logs:
